# Generated by Django 5.0.1 on 2025-03-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='modalidade',
            field=models.CharField(choices=[('EAD', 'Ensino à Distância'), ('PRESENCIAL', 'Ensino Presencial')], default='EAD', max_length=10, verbose_name='Modalidade de Ensino'),
        ),
    ]
