# Generated by Django 5.0.1 on 2025-03-03 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('nota_prova', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota da Prova')),
                ('nota_pim', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota do PIM')),
                ('nota_ava', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota dos Questionários AVA')),
                ('nota_exame', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota do Exame')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['-created_at'],
            },
        ),
    ]
